mystr = "harry is a good boy"
print(len (mystr))
print(mystr[0:5])
print(mystr[2:15:])
print(mystr[::2])
print(mystr[::5559])
print(mystr[-1:0])
print(mystr[-4:-2])
print(mystr[::-2])
print(mystr[::-1])
print(type(mystr))
print((mystr.isalnum()))
print((mystr.isalpha()))
print((mystr.endswith("boy")))
print((mystr.count("r")))
print(mystr.capitalize())
print(mystr.find("good"))
print(mystr.upper())
print(mystr.lower())
print(mystr.replace("is","are"))